site_name: MoreValheim
theme:
  name: 'material'
  palette:
    scheme: preference
    primary: blue grey
  favicon: favicon.png
  logo: favicon.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
google_analytics:
  - UA-G-FLVM79PMME
  - auto