site_name: MoreValheim
theme:
  name: 'material'
  palette:
    scheme: preference
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true